### ISSUE TITLE
Var Naming

### ISSUE THREAD

**Issue by charlychiu** [shrimp509/MemeFragment#1]
https://github.com/shrimp509/MemeFragment/blob/2e64515b4315ce2047149b7a976b40bda6160e79/app/src/main/java/ncku/csie/iir/rongson/buckyfragment/TopSectionFragment.java#L22

**Comment by shrimp509** [comment]
Excuse me, anything wrong?
Could you please explain your thought? Thanks.

In my opinion, this interface is taking two strings from top and bottom  to create a meme.

**Comment by shrimp509** [comment]
@charlychiu Renamed it, please take a look.
https://github.com/shrimp509/MemeFragment/blob/12183190f3c3ac3b2b43d2566df0d964c606e607/app/src/main/java/ncku/csie/iir/rongson/buckyfragment/TopSectionFragment.java#L21-L23

**Comment by charlychiu** [comment]
LGTM ~
